// Generated by Wrangler on Mon Jun 17 2024 14:03:18 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	GOVEE_DEVICE_ID: "AC:C0:CB:32:37:36:7A:6D";
	GOVEE_MODEL_ID: "H6052";
	GOVEE_API_KEY: string;
	AI: Ai;
}
